#Project Information
site_name: TSInterpret
site_description: TSInterpret is a Python library for interpretable time series classification.
site_author: Jacqueline Höllig
site_url:  https://fzi-forschungszentrum-informatik.github.io/TSInterpret/

# Repository
repo_name: TSInterpret
repo_url:  https://fzi-forschungszentrum-informatik.github.io/TSInterpret/
edit_uri: "https://fzi-forschungszentrum-informatik.github.io/TSInterpret/"

copyright: Copyright &copy; 2019 - 2022

theme:
  name: "material"
  font: false
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - def_list
  - footnotes
  - attr_list
  - md_in_html

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          docstring_section_style: spacy
          show_source: False
          merge_init_into_class: True
- mkdocs-jupyter:
    execute: False
- bibtex:
      bib_file: "library.bib"



nav:
  - Home: index.md
  - Getting Started: GettingStarted.md
  - Interpretability: Interpretability.md
  - Algorithm Overview: AlgorithmOverview.md
  - How-To:
    - Instance-Based Methods: 
      - Counterfactuals:
        - Ates: ./Notebooks/Ates_torch.ipynb
        - Nun-CF: ./Notebooks/NunCF_torch.ipynb
        - TSEvo: ./Notebooks/TSEvo_torch.ipynb
        - SETS: ./Notebooks/Sets_tensorflow.ipynb
    - Feature Attribution Methods:
      - Leftist: ./Notebooks/Leftist_torch.ipynb
      - Saliency: ./Notebooks/TSR_torch.ipynb
  - API References: 
    - Bases:
      - Instance Based:  ./Methods/CF.md
      - Feature Attribution: ./Methods/Saliency.md
    - Methods: 
      - Counterfactual:
        - TSEvo: ./Methods/TSEvo.md
        - COMTE: ./Methods/COMTE.md
        - NUNCF: ./Methods/NunCF.md
        - SETS: ./Methods/SETS.md
      - TSR: ./Methods/Saliency.md
      - LEFTIST: ./Methods/Leftist.md